<template><div><h1 id="musics-🎧" tabindex="-1"><a class="header-anchor" href="#musics-🎧"><span>Musics 🎧</span></a></h1>
<div class="hint-container info">
<p class="hint-container-title">정보</p>
<p>최근 개인적으로 즐겨 듣고 있는 곡들을 정리해둔 공간입니다.<br>
감상은 <a href="https://open.spotify.com/" target="_blank" rel="noopener noreferrer">Spotify</a> 또는 <a href="https://www.youtube.com/" target="_blank" rel="noopener noreferrer">YouTube</a>를 통해 가능합니다.<br>
번호는 순위가 아닌 임의로 부여된 것입니다. 재생목록은 수시로 update될 것입니다.</p>
</div>
<h3 id="_1-너에게-닿기를" tabindex="-1"><a class="header-anchor" href="#_1-너에게-닿기를"><span>1. 너에게 닿기를</span></a></h3>
<iframe style="border-radius:12px" src="https://open.spotify.com/embed/track/20QI1DhCFz7pN8rATkNguv?utm_source=generator" width="100%" height="152" frameBorder="0" allowfullscreen="" allow="autoplay; clipboard-write; encrypted-media; fullscreen; picture-in-picture" loading="lazy"></iframe>
<iframe style="border-radius:12px" width="100%" height="152" src="https://www.youtube.com/embed/Ry1RrIVyl1M?controls=1&modestbranding=1" frameborder="0" allow="autoplay; clipboard-write; encrypted-media; fullscreen; picture-in-picture" allowfullscreen loading="lazy"></iframe>
<h3 id="_2-hot" tabindex="-1"><a class="header-anchor" href="#_2-hot"><span>2. HOT</span></a></h3>
<iframe style="border-radius:12px" src="https://open.spotify.com/embed/track/406IpEtZPvbxApWTGM3twY?utm_source=generator" width="100%" height="152" frameBorder="0" allowfullscreen="" allow="autoplay; clipboard-write; encrypted-media; fullscreen; picture-in-picture" loading="lazy"></iframe>
<iframe style="border-radius:12px" width="100%" height="152" src="https://www.youtube.com/embed/cCkAcVOS3ig?controls=1&modestbranding=1" frameborder="0" allow="autoplay; clipboard-write; encrypted-media; fullscreen; picture-in-picture" allowfullscreen loading="lazy"></iframe>
<h3 id="_3-journey" tabindex="-1"><a class="header-anchor" href="#_3-journey"><span>3. Journey</span></a></h3>
<iframe style="border-radius:12px" src="https://open.spotify.com/embed/track/6dxgKYAH0TvoSb16xD30rD?utm_source=generator" width="100%" height="152" frameBorder="0" allowfullscreen="" allow="autoplay; clipboard-write; encrypted-media; fullscreen; picture-in-picture" loading="lazy"></iframe>
<iframe style="border-radius:12px" width="100%" height="152" src="https://www.youtube.com/embed/3VOerLGIMG4?controls=1&modestbranding=1" frameborder="0" allow="autoplay; clipboard-write; encrypted-media; fullscreen; picture-in-picture" allowfullscreen loading="lazy"></iframe>
<h3 id="_4-good-day-2025-telepathy-by-the-moonlight-window" tabindex="-1"><a class="header-anchor" href="#_4-good-day-2025-telepathy-by-the-moonlight-window"><span>4. Good Day 2025 (Telepathy + By the Moonlight Window)</span></a></h3>
<iframe style="border-radius:12px" src="https://open.spotify.com/embed/track/4SinziOMDPR58wWHakWP9v?utm_source=generator" width="100%" height="152" frameBorder="0" allowfullscreen="" allow="autoplay; clipboard-write; encrypted-media; fullscreen; picture-in-picture" loading="lazy"></iframe>
<iframe style="border-radius:12px" width="100%" height="152" src="https://www.youtube.com/embed/cRfbII60IjY?controls=1&modestbranding=1" frameborder="0" allow="autoplay; clipboard-write; encrypted-media; fullscreen; picture-in-picture" allowfullscreen loading="lazy"></iframe>
<h3 id="_5-missing-you-feat-김윤아-of-자우림" tabindex="-1"><a class="header-anchor" href="#_5-missing-you-feat-김윤아-of-자우림"><span>5. Missing You (Feat. 김윤아 of 자우림)</span></a></h3>
<iframe style="border-radius:12px" src="https://open.spotify.com/embed/track/3BqfHyw9cLm6POreivziWN?utm_source=generator" width="100%" height="152" frameBorder="0" allowfullscreen="" allow="autoplay; clipboard-write; encrypted-media; fullscreen; picture-in-picture" loading="lazy"></iframe>
<iframe style="border-radius:12px" width="100%" height="152" src="https://www.youtube.com/embed/XNSmuTpzr8U?controls=1&modestbranding=1" frameborder="0" allow="autoplay; clipboard-write; encrypted-media; fullscreen; picture-in-picture" allowfullscreen loading="lazy"></iframe>
<h3 id="_6-달빛-소년" tabindex="-1"><a class="header-anchor" href="#_6-달빛-소년"><span>6. 달빛 소년</span></a></h3>
<iframe style="border-radius:12px" src="https://open.spotify.com/embed/track/3QLaYOmG5rEvIgIJ90nhXd?utm_source=generator" width="100%" height="152" frameBorder="0" allowfullscreen="" allow="autoplay; clipboard-write; encrypted-media; fullscreen; picture-in-picture" loading="lazy"></iframe>
<iframe style="border-radius:12px" width="100%" height="152" src="https://www.youtube.com/embed/EapUSbnsIws?controls=1&modestbranding=1" frameborder="0" allow="autoplay; clipboard-write; encrypted-media; fullscreen; picture-in-picture" allowfullscreen loading="lazy"></iframe>
<h3 id="_7-관객이-될게-i-stan-u" tabindex="-1"><a class="header-anchor" href="#_7-관객이-될게-i-stan-u"><span>7. 관객이 될게 (I stan U)</span></a></h3>
<iframe style="border-radius:12px" src="https://open.spotify.com/embed/track/0NnXG9qhpf0E6elVQdWLE7?utm_source=generator" width="100%" height="152" frameBorder="0" allowfullscreen="" allow="autoplay; clipboard-write; encrypted-media; fullscreen; picture-in-picture" loading="lazy"></iframe>
<iframe style="border-radius:12px" width="100%" height="152" src="https://www.youtube.com/embed/_ZfT3M6ZKEM?controls=1&modestbranding=1" frameborder="0" allow="autoplay; clipboard-write; encrypted-media; fullscreen; picture-in-picture" allowfullscreen loading="lazy"></iframe>
<h3 id="_8-no-boss-feat-dok2" tabindex="-1"><a class="header-anchor" href="#_8-no-boss-feat-dok2"><span>8. No Boss (Feat. Dok2)</span></a></h3>
<iframe style="border-radius:12px" src="https://open.spotify.com/embed/track/13189A36QorREwPdLYzFIs?utm_source=generator" width="100%" height="152" frameBorder="0" allowfullscreen="" allow="autoplay; clipboard-write; encrypted-media; fullscreen; picture-in-picture" loading="lazy"></iframe>
<iframe style="border-radius:12px" width="100%" height="152" src="https://www.youtube.com/embed/ZmKB_0tecKM?controls=1&modestbranding=1" frameborder="0" allow="autoplay; clipboard-write; encrypted-media; fullscreen; picture-in-picture" allowfullscreen loading="lazy"></iframe>
<h3 id="_9-초대" tabindex="-1"><a class="header-anchor" href="#_9-초대"><span>9. 초대</span></a></h3>
<iframe style="border-radius:12px" src="https://open.spotify.com/embed/track/5SGoHeqHhU62drrUO1QoyA?utm_source=generator" width="100%" height="152" frameBorder="0" allowfullscreen="" allow="autoplay; clipboard-write; encrypted-media; fullscreen; picture-in-picture" loading="lazy"></iframe>
<iframe style="border-radius:12px" width="100%" height="152" src="https://www.youtube.com/embed/cjS6tvGnpxg?controls=1&modestbranding=1" frameborder="0" allow="autoplay; clipboard-write; encrypted-media; fullscreen; picture-in-picture" allowfullscreen loading="lazy"></iframe>
<h3 id="_10-민들레-single-ver" tabindex="-1"><a class="header-anchor" href="#_10-민들레-single-ver"><span>10. 민들레 - single ver.</span></a></h3>
<iframe style="border-radius:12px" src="https://open.spotify.com/embed/track/3eOXiUUfz9OhyVqoREsJYe?utm_source=generator" width="100%" height="152" frameBorder="0" allowfullscreen="" allow="autoplay; clipboard-write; encrypted-media; fullscreen; picture-in-picture" loading="lazy"></iframe>
<iframe style="border-radius:12px" width="100%" height="152" src="https://www.youtube.com/embed/qr9i9jRuTug?controls=1&modestbranding=1" frameborder="0" allow="autoplay; clipboard-write; encrypted-media; fullscreen; picture-in-picture" allowfullscreen loading="lazy"></iframe>
<h3 id="_11-사포닌-같은-너" tabindex="-1"><a class="header-anchor" href="#_11-사포닌-같은-너"><span>11. 사포닌 같은 너</span></a></h3>
<iframe style="border-radius:12px" src="https://open.spotify.com/embed/track/1MrSkch4hdGTGeMlcbZkpo?utm_source=generator" width="100%" height="152" frameBorder="0" allowfullscreen="" allow="autoplay; clipboard-write; encrypted-media; fullscreen; picture-in-picture" loading="lazy"></iframe>
<iframe style="border-radius:12px" width="100%" height="152" src="https://www.youtube.com/embed/kPHJonG_3N0?controls=1&modestbranding=1" frameborder="0" allow="autoplay; clipboard-write; encrypted-media; fullscreen; picture-in-picture" allowfullscreen loading="lazy"></iframe>
<h3 id="_12-파도" tabindex="-1"><a class="header-anchor" href="#_12-파도"><span>12. 파도</span></a></h3>
<iframe style="border-radius:12px" src="https://open.spotify.com/embed/track/4LWmsKMaSxyiHByibfOIwV?utm_source=generator" width="100%" height="152" frameBorder="0" allowfullscreen="" allow="autoplay; clipboard-write; encrypted-media; fullscreen; picture-in-picture" loading="lazy"></iframe>
<iframe style="border-radius:12px" width="100%" height="152" src="https://www.youtube.com/embed/35KLXum5uD8?controls=1&modestbranding=1" frameborder="0" allow="autoplay; clipboard-write; encrypted-media; fullscreen; picture-in-picture" allowfullscreen loading="lazy"></iframe>
<h3 id="_13-봄바람-feat-나얼" tabindex="-1"><a class="header-anchor" href="#_13-봄바람-feat-나얼"><span>13. 봄바람 (FEAT.나얼)</span></a></h3>
<iframe style="border-radius:12px" src="https://open.spotify.com/embed/track/2LD3U3IY43B9wIW7V1DEiO?utm_source=generator" width="100%" height="152" frameBorder="0" allowfullscreen="" allow="autoplay; clipboard-write; encrypted-media; fullscreen; picture-in-picture" loading="lazy"></iframe>
<iframe style="border-radius:12px" width="100%" height="152" src="https://www.youtube.com/embed/VEWJlmw7CO8?controls=1&modestbranding=1" frameborder="0" allow="autoplay; clipboard-write; encrypted-media; fullscreen; picture-in-picture" allowfullscreen loading="lazy"></iframe>
<h3 id="_14-hate-rodrigo-feat-우기" tabindex="-1"><a class="header-anchor" href="#_14-hate-rodrigo-feat-우기"><span>14. Hate Rodrigo (Feat. 우기)</span></a></h3>
<iframe style="border-radius:12px" src="https://open.spotify.com/embed/track/5ms7rcVKjBFUtoVh8hE0Y9?utm_source=generator" width="100%" height="152" frameBorder="0" allowfullscreen="" allow="autoplay; clipboard-write; encrypted-media; fullscreen; picture-in-picture" loading="lazy"></iframe>
<iframe style="border-radius:12px" width="100%" height="152" src="https://www.youtube.com/embed/uTKYOio9KAk?controls=1&modestbranding=1" frameborder="0" allow="autoplay; clipboard-write; encrypted-media; fullscreen; picture-in-picture" allowfullscreen loading="lazy"></iframe>
<h3 id="_15-like-crazy" tabindex="-1"><a class="header-anchor" href="#_15-like-crazy"><span>15. Like Crazy</span></a></h3>
<iframe style="border-radius:12px" src="https://open.spotify.com/embed/track/3Ua0m0YmEjrMi9XErKcNiR?utm_source=generator" width="100%" height="152" frameBorder="0" allowfullscreen="" allow="autoplay; clipboard-write; encrypted-media; fullscreen; picture-in-picture" loading="lazy"></iframe>
<iframe style="border-radius:12px" width="100%" height="152" src="https://www.youtube.com/embed/YuR6kRxBFAk?controls=1&modestbranding=1" frameborder="0" allow="autoplay; clipboard-write; encrypted-media; fullscreen; picture-in-picture" allowfullscreen loading="lazy"></iframe>
<h3 id="_16-like-jennie" tabindex="-1"><a class="header-anchor" href="#_16-like-jennie"><span>16. like JENNIE</span></a></h3>
<iframe style="border-radius:12px" src="https://open.spotify.com/embed/track/0DC62SYIRKMFgx2f7OyvwD?utm_source=generator" width="100%" height="152" frameBorder="0" allowfullscreen="" allow="autoplay; clipboard-write; encrypted-media; fullscreen; picture-in-picture" loading="lazy"></iframe>
<iframe style="border-radius:12px" width="100%" height="152" src="https://www.youtube.com/embed/bwzrdr9nDiI?controls=1&modestbranding=1" frameborder="0" allow="autoplay; clipboard-write; encrypted-media; fullscreen; picture-in-picture" allowfullscreen loading="lazy"></iframe>
<h3 id="_17-오늘만-i-love-you" tabindex="-1"><a class="header-anchor" href="#_17-오늘만-i-love-you"><span>17. 오늘만 I LOVE YOU</span></a></h3>
<iframe style="border-radius:12px" src="https://open.spotify.com/embed/track/7GOIrZTegzVty8mhNhRuA0?utm_source=generator" width="100%" height="152" frameBorder="0" allowfullscreen="" allow="autoplay; clipboard-write; encrypted-media; fullscreen; picture-in-picture" loading="lazy"></iframe>
<iframe style="border-radius:12px" width="100%" height="152" src="https://www.youtube.com/embed/0MJjPYgaLNQ?controls=1&modestbranding=1" frameborder="0" allow="autoplay; clipboard-write; encrypted-media; fullscreen; picture-in-picture" allowfullscreen loading="lazy"></iframe>
<h3 id="_18-내게-사랑이-뭐냐고-물어본다면" tabindex="-1"><a class="header-anchor" href="#_18-내게-사랑이-뭐냐고-물어본다면"><span>18. 내게 사랑이 뭐냐고 물어본다면</span></a></h3>
<iframe style="border-radius:12px" src="https://open.spotify.com/embed/track/5zsMOF3yWT4U1Vw5eaMQFH?utm_source=generator" width="100%" height="152" frameBorder="0" allowfullscreen="" allow="autoplay; clipboard-write; encrypted-media; fullscreen; picture-in-picture" loading="lazy"></iframe>
<iframe style="border-radius:12px" width="100%" height="152" src="https://www.youtube.com/embed/5ly8tAU-n_w?controls=1&modestbranding=1" frameborder="0" allow="autoplay; clipboard-write; encrypted-media; fullscreen; picture-in-picture" allowfullscreen loading="lazy"></iframe>
<h3 id="_19-어푸-ah-puh" tabindex="-1"><a class="header-anchor" href="#_19-어푸-ah-puh"><span>19. 어푸 (Ah puh)</span></a></h3>
<iframe style="border-radius:12px" src="https://open.spotify.com/embed/track/1IJxbEXfgiKuRx6oXMX87e?utm_source=generator" width="100%" height="152" frameBorder="0" allowfullscreen="" allow="autoplay; clipboard-write; encrypted-media; fullscreen; picture-in-picture" loading="lazy"></iframe>
<iframe style="border-radius:12px" width="100%" height="152" src="https://www.youtube.com/embed/7n9D8ZeOQv0?controls=1&modestbranding=1" frameborder="0" allow="autoplay; clipboard-write; encrypted-media; fullscreen; picture-in-picture" allowfullscreen loading="lazy"></iframe>
<h3 id="_20-beautiful-things" tabindex="-1"><a class="header-anchor" href="#_20-beautiful-things"><span>20. Beautiful Things</span></a></h3>
<iframe style="border-radius:12px" src="https://open.spotify.com/embed/track/6tNQ70jh4OwmPGpYy6R2o9?utm_source=generator" width="100%" height="152" frameBorder="0" allowfullscreen="" allow="autoplay; clipboard-write; encrypted-media; fullscreen; picture-in-picture" loading="lazy"></iframe>
<iframe style="border-radius:12px" width="100%" height="152" src="https://www.youtube.com/embed/QcgPEv2BIpE?controls=1&modestbranding=1" frameborder="0" allow="autoplay; clipboard-write; encrypted-media; fullscreen; picture-in-picture" allowfullscreen loading="lazy"></iframe></div></template>


